"""
RAMA Ghost Coder — watches your GitHub repo at night,
auto-fixes issues, and opens Pull Requests by morning.
"""

import asyncio, json, logging, os
from datetime import datetime
import aiohttp

logger = logging.getLogger("rama.ghost_coder")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


class GhostCoder:
    def __init__(self, repo: str = ""):
        """
        repo: 'owner/repo-name'
        """
        self.repo = repo
        self.base_url = f"https://api.github.com/repos/{repo}"
        self._session = None

    async def _get_session(self):
        if not self._session or self._session.closed:
            self._session = aiohttp.ClientSession(headers=HEADERS)
        return self._session

    # ── Fetch open issues ─────────────────────────────────────────────────
    async def fetch_open_issues(self) -> list:
        session = await self._get_session()
        async with session.get(f"{self.base_url}/issues?state=open&per_page=10") as r:
            if r.status == 200:
                issues = await r.json()
                return [
                    {
                        "number": i["number"],
                        "title": i["title"],
                        "body": (i.get("body") or "")[:500],
                        "labels": [l["name"] for l in i.get("labels", [])],
                    }
                    for i in issues
                    if "pull_request" not in i   # skip PRs
                ]
        return []

    # ── Generate a fix using Gemini / local LLM ───────────────────────────
    async def generate_fix(self, issue: dict, gemini=None) -> str:
        prompt = (
            f"GitHub Issue #{issue['number']}: {issue['title']}\n\n"
            f"{issue['body']}\n\n"
            "Write a concise Python/TypeScript fix or solution for this issue. "
            "Include the file path as a comment at the top."
        )
        if gemini:
            try:
                r = gemini.generate_content(prompt)
                return r.text
            except Exception as e:
                logger.error(f"Gemini fix failed: {e}")
        return f"# Auto-fix for issue #{issue['number']}: {issue['title']}\n# TODO: implement fix\npass"

    # ── Create a branch ───────────────────────────────────────────────────
    async def create_branch(self, branch_name: str, base: str = "main") -> bool:
        session = await self._get_session()
        # Get base SHA
        async with session.get(f"{self.base_url}/git/refs/heads/{base}") as r:
            if r.status != 200:
                return False
            data = await r.json()
            sha = data["object"]["sha"]

        # Create branch
        async with session.post(
            f"{self.base_url}/git/refs",
            json={"ref": f"refs/heads/{branch_name}", "sha": sha},
        ) as r:
            return r.status in (200, 201, 422)  # 422 = already exists

    # ── Open a Pull Request ───────────────────────────────────────────────
    async def open_pr(self, issue: dict, fix_code: str) -> dict:
        branch = f"rama-fix-issue-{issue['number']}"
        await self.create_branch(branch)

        session = await self._get_session()
        pr_body = (
            f"## RAMA Auto-Fix for #{issue['number']}\n\n"
            f"**Issue:** {issue['title']}\n\n"
            f"**Generated fix:**\n```\n{fix_code[:800]}\n```\n\n"
            f"*Generated by RAMA Ghost Coder at {datetime.utcnow().isoformat()}*\n"
            f"*Please review before merging.*"
        )
        async with session.post(
            f"{self.base_url}/pulls",
            json={
                "title": f"[RAMA] Fix: {issue['title'][:60]}",
                "body": pr_body,
                "head": branch,
                "base": "main",
            },
        ) as r:
            if r.status in (200, 201):
                data = await r.json()
                return {"status": "opened", "url": data.get("html_url"), "branch": branch}
            return {"status": "error", "code": r.status}

    # ── Nightly loop ──────────────────────────────────────────────────────
    async def nightly_loop(self, gemini=None, interval_hours: float = 6):
        logger.info(f"Ghost Coder watching repo: {self.repo}")
        while True:
            try:
                issues = await self.fetch_open_issues()
                logger.info(f"Ghost Coder found {len(issues)} open issues")
                for issue in issues[:3]:  # max 3 per run
                    fix = await self.generate_fix(issue, gemini)
                    result = await self.open_pr(issue, fix)
                    logger.info(f"Issue #{issue['number']} → PR {result}")
            except Exception as e:
                logger.error(f"Ghost Coder error: {e}")
            await asyncio.sleep(interval_hours * 3600)

    async def close(self):
        if self._session and not self._session.closed:
            await self._session.close()
